_format_version: '3.0'
services:
- name: mockbin-service-1
  url: http://mockbin.com/request
  routes:
    - name: mockbin-url-1
      protocols:
        - "http"
        - "https"
      paths:
        - /
  plugins:
  - name: header-validation
    config:
      header_key: api_key
- name: pokemon-service-1
  url: https://pokeapi.co/api/v2/pokemon
  routes:
    - protocols:
        - "http"
        - "https"
      paths:
        - "/pokemon"
  plugins:
  - name: header-validation
    config:
      header_key: api_key
- name: digimon-service-1
  url: https://www.digi-api.com/api/v1/digimon/
  routes:
    - protocols:
        - "http"
        - "https"
      paths:
        - "/digimon"
  plugins:
  - name: header-validation
    config:
      header_key: api_key